import React, { useState, useEffect, useRef } from "react";
import {
  Bot, X, Send, Sparkles, ChevronDown, ChevronUp,
  ShieldCheck, HelpCircle, ArrowRight, MessageSquare,
  BookOpen, Scale, CheckCircle2, Zap, RefreshCw, ExternalLink
} from "lucide-react";

const COPILOT_KNOWLEDGE_BASE = [
  {
    keywords: ["verify", "verification", "document", "authenticity", "authentic", "ocr", "udin", "fake"],
    response: "🤖 **AI Document & Gateway Verification:**\n\nTenderTrust uses a **Zero-Trust Multi-Tiered Verification Pipeline**:\n1. **Document AI (OCR)** extracts text, CA UDIN codes, balance sheets, and dates.\n2. **8-Government Portal Sync**: Live API queries verify data with **GSTN**, **MCA21**, **MSME Udyam**, **Income Tax PAN**, **EPFO/ESIC**, **DPIIT**, **CVC Debarment**, and **MII Desk**.\n3. **Cross-Data Triangulation**: Compares claimed turnover vs MCA21 audited returns vs GSTR-3B monthly filings to detect turnover inflation, forged UDINs, or shell entities."
  },
  {
    keywords: ["gfr 144", "rule 144", "confidential", "dossier", "competitor"],
    response: "📜 **GFR Rule 144 & 144(i) (Fundamental Principles of Public Procurement):**\n\n• **Confidentiality:** Competing bidder technical evaluations, pricing strategies, and internal risk scores are strictly confidential and restricted to the Procurement Officer.\n• **Statutory Due Diligence:** The Procurement Officer must verify technical competence, financial standing, and manufacturing capacity before contract award."
  },
  {
    keywords: ["crac", "10 day", "10-day", "consignee", "inspection", "acceptance"],
    response: "📦 **Consignee Receipt and Acceptance Certificate (CRAC) Workflow:**\n\n• **10-Day Mandatory SLA:** Under GeM GFR guidelines, the Consignee must inspect and issue CRAC within **10 calendar days** of physical goods arrival.\n• **Auto-Generation:** If no rejection is recorded within 10 days, CRAC is auto-generated by the system.\n• **GPA Escrow Release:** Issuing CRAC authorizes the instant release of payment from the GeM Pool Account (GPA) directly to the supplier's bank account."
  },
  {
    keywords: ["ra", "reverse auction", "decrement", "auction", "auto-extension", "bids"],
    response: "⚡ **GeM Reverse Auction (RA) Rules:**\n\n• **Dynamic Auto-Extension:** If a lower L-1 bid is submitted within the last 10 minutes, the auction timer automatically extends by **+15 minutes**.\n• **Min Decrement Step:** Bidders must decrease quotes by at least the specified minimum decrement step (e.g. ₹50,000 or ₹2 Lakhs).\n• **Anonymized Ticker:** Competitors see real-time L-1 price progression while bidder identities remain masked (e.g., Bidder_A92)."
  },
  {
    keywords: ["gfr 149", "direct purchase", "direct po", "5 lakh", "25000"],
    response: "🛒 **GFR Rule 149 (Procurement through GeM):**\n\n• **Up to ₹25,000:** Direct Purchase permitted from any verified supplier meeting required specifications.\n• **₹25,001 to ₹5,00,000:** Mandatory comparison of at least **3 different OEMs** on GeM, selecting the lowest price (L-1).\n• **Above ₹5,00,000:** Mandatory Public Tender Bid or Reverse Auction (RA)."
  },
  {
    keywords: ["msme", "25%", "startup", "exemption", "mii", "make in india"],
    response: "🇮🇳 **MSME & Make in India (MII) Statutory Mandates:**\n\n• **25% MSME Mandate:** Central Ministries must procure at least 25% of annual volume from Micro & Small Enterprises (with 4% reserved for SC/ST and 3% for Women MSEs).\n• **MII Class-1 (≥50% Local Content):** Given statutory purchase preference over foreign goods.\n• **Startup Exemption:** DPIIT registered startups are eligible for exemption from prior turnover and past experience under GFR Rule 173(i)."
  },
  {
    keywords: ["role", "switch", "officer", "buyer", "seller", "permission"],
    response: "👥 **User Roles & Navigation in TenderTrust:**\n\n1. **Procurement Officer**: Authority for multi-portal verification, AI evidence inspection, and Class-3 DSC digital decision signing (Landing: *AI Compliance Engine*).\n2. **Buyer Desk**: Department indentor for drafting RFPs, direct catalog POs, and CRAC inspection (Landing: *Marketplace Catalog*).\n3. **Seller Desk**: Registered vendor portal for pre-check tests, sealed bid submissions, and RA bidding (Landing: *Seller & OEM Hub*)."
  }
];

export default function FloatingCopilot({ activeTab, currentUser, onSelectTab }) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([
    {
      id: 1,
      sender: "copilot",
      text: "👋 Namaste! I am your **TenderTrust AI Copilot**.\n\nI can assist you with GFR-2017 statutory procurement rules, 8-gateway cross-verification, CRAC 10-day SLAs, and platform workflows. How can I help you today?",
      time: "Just now"
    }
  ]);
  const [inputQuery, setInputQuery] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);

  // Contextual Hint based on activeTab
  const getContextualHint = () => {
    switch (activeTab) {
      case "LANDING":
        return "🇮🇳 GeM Public Portal: Explore top bidders, verified OEM sellers, and national procurement statistics. Click any role sign-in button to enter your workspace.";
      case "DOSSIER":
        return "🔍 Viewing AI Compliance Dossier: I can explain the 8-portal cross proofs, UDIN verification, or how to apply Class-3 DSC seals.";
      case "MARKETPLACE":
        return "🛒 Viewing GeM Catalog: Ask about GFR 149 Direct Purchase limits, L-1 comparison rules, or MSME 25% filters.";
      case "BIDS_RA":
        return "⚡ Viewing Bids & Reverse Auction: Ask about +15 min auto-extensions, min decrements, or sealed bid rules.";
      case "BUYER_CONSOLE":
        return "🏛️ Viewing Buyer Desk: Ask about the 10-day CRAC inspection deadline or GeM Pool Account (GPA) escrow releases.";
      case "SELLER_PORTAL":
        return "🏢 Viewing Seller Hub: Ask how to run the Self Pre-Check Tool or download qualified compliance certificates.";
      case "IMS":
        return "⚖️ Viewing Incident Management: Ask about Show Cause notice timelines, 10% LD penalties, or GFR 151 debarment rules.";
      case "ANALYTICS":
        return "📊 Viewing GeM Analytics: Ask about National GMV growth, MSME share tracking, or API gateway uptime.";
      case "RULES":
        return "📖 Viewing GFR Rules: Ask about any clause under General Financial Rules 2017 (Rule 144, 149, 151, 175).";
      default:
        return "🤖 Ask me anything about GeM procurement, statutory compliance, or platform workflows.";
    }
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    if (isOpen) {
      scrollToBottom();
    }
  }, [messages, isOpen]);

  const handleSend = (textToSend = null) => {
    const query = (textToSend || inputQuery).trim();
    if (!query) return;

    const userMsg = {
      id: Date.now(),
      sender: "user",
      text: query,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages(prev => [...prev, userMsg]);
    setInputQuery("");
    setIsTyping(true);

    setTimeout(() => {
      setIsTyping(false);
      const lowerQ = query.toLowerCase();

      // Find best match in knowledge base
      let matched = COPILOT_KNOWLEDGE_BASE.find(k =>
        k.keywords.some(kw => lowerQ.includes(kw))
      );

      let responseText = "";
      if (matched) {
        responseText = matched.response;
      } else if (lowerQ.includes("hi") || lowerQ.includes("hello") || lowerQ.includes("help")) {
        responseText = "Hello! I am ready to guide you through GeM-CompliAI. You can ask me questions like:\n• *How does AI verify document authenticity?*\n• *Explain the 10-day CRAC rule.*\n• *What are GFR Rule 149 direct purchase limits?*\n• *How does the Reverse Auction auto-extension work?*";
      } else {
        responseText = `🤖 **GeM Compliance Intelligence:**\n\nRegarding **"${query}"**:\nAll procurement on this portal conforms to the **General Financial Rules (GFR) 2017** and official GeM guidelines. The AI engine continuously audits participating bidders across 8 authoritative government gateways to ensure 100% statutory compliance before tender awards.\n\n*Would you like to explore the GFR Rules Compendium or inspect the live Bidder Matrix?*`;
      }

      const copilotMsg = {
        id: Date.now() + 1,
        sender: "copilot",
        text: responseText,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };

      setMessages(prev => [...prev, copilotMsg]);
    }, 700);
  };

  const quickPills = [
    "How does AI verify documents?",
    "Explain 10-day CRAC rule",
    "GFR 149 Direct Purchase limits",
    "How does Reverse Auction work?",
    "MSME & Make in India rules"
  ];

  return (
    <div style={{ position: "fixed", bottom: "24px", right: "24px", zIndex: 9999, fontFamily: "var(--font-sans)" }}>
      
      {/* Expanded Copilot Modal Window */}
      {isOpen && (
        <div style={{
          width: "410px",
          height: "560px",
          background: "#FFFFFF",
          borderRadius: "12px",
          boxShadow: "0 12px 36px rgba(10, 37, 64, 0.25), 0 4px 12px rgba(0,0,0,0.1)",
          border: "1px solid #CBD5E1",
          display: "flex",
          flexDirection: "column",
          marginBottom: "12px",
          overflow: "hidden",
          animation: "fadeInUp 0.2s ease-out"
        }}>
          
          {/* Header */}
          <div style={{
            background: "linear-gradient(135deg, #0A2540 0%, #163E66 100%)",
            color: "#FFFFFF",
            padding: "0.85rem 1rem",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center"
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: "0.6rem" }}>
              <div style={{
                width: "32px",
                height: "32px",
                borderRadius: "50%",
                background: "var(--gem-orange)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                boxShadow: "0 2px 6px rgba(244,121,32,0.4)"
              }}>
                <Bot size={18} color="#FFFFFF" />
              </div>
              <div>
                <div style={{ fontSize: "0.88rem", fontWeight: 800, letterSpacing: "-0.01em" }}>
                  TenderTrust AI Compliance Copilot
                </div>
                <div style={{ fontSize: "0.68rem", color: "#93C5FD", display: "flex", alignItems: "center", gap: "0.3rem" }}>
                  <div style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#10B981" }} />
                  <span>Online • GFR 2017 & 8 Gateways Active</span>
                </div>
              </div>
            </div>

            <button
              onClick={() => setIsOpen(false)}
              style={{
                background: "rgba(255,255,255,0.15)",
                border: "none",
                borderRadius: "6px",
                color: "#FFFFFF",
                width: "28px",
                height: "28px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                cursor: "pointer"
              }}
              title="Minimize Copilot"
            >
              <X size={16} />
            </button>
          </div>

          {/* Context Banner */}
          <div style={{
            background: "var(--gem-orange-light)",
            borderBottom: "1px solid rgba(244,121,32,0.2)",
            padding: "0.4rem 0.85rem",
            fontSize: "0.72rem",
            color: "#78350F",
            display: "flex",
            alignItems: "center",
            gap: "0.4rem"
          }}>
            <Sparkles size={13} color="var(--gem-orange-dark)" style={{ flexShrink: 0 }} />
            <span style={{ lineHeight: 1.3 }}>{getContextualHint()}</span>
          </div>

          {/* Chat Messages Log */}
          <div style={{
            flex: 1,
            padding: "0.85rem",
            overflowY: "auto",
            display: "flex",
            flexDirection: "column",
            gap: "0.75rem",
            background: "#F8FAFC"
          }}>
            {messages.map(msg => (
              <div
                key={msg.id}
                style={{
                  alignSelf: msg.sender === "user" ? "flex-end" : "flex-start",
                  maxWidth: "88%",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: msg.sender === "user" ? "flex-end" : "flex-start"
                }}
              >
                <div style={{
                  background: msg.sender === "user" ? "var(--gem-navy)" : "#FFFFFF",
                  color: msg.sender === "user" ? "#FFFFFF" : "var(--text-primary)",
                  padding: "0.6rem 0.8rem",
                  borderRadius: msg.sender === "user" ? "10px 10px 2px 10px" : "10px 10px 10px 2px",
                  fontSize: "0.78rem",
                  lineHeight: 1.45,
                  boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
                  border: msg.sender === "user" ? "none" : "1px solid var(--border-light)",
                  whiteSpace: "pre-wrap"
                }}>
                  {msg.text}
                </div>
                <span style={{ fontSize: "0.65rem", color: "var(--text-muted)", marginTop: "0.15rem", padding: "0 0.2rem" }}>
                  {msg.time}
                </span>
              </div>
            ))}

            {isTyping && (
              <div style={{ alignSelf: "flex-start", background: "#FFFFFF", padding: "0.5rem 0.75rem", borderRadius: "10px 10px 10px 2px", border: "1px solid var(--border-light)", fontSize: "0.75rem", color: "var(--text-muted)", display: "flex", alignItems: "center", gap: "0.4rem" }}>
                <RefreshCw size={12} className="spin" />
                <span>GeM Copilot analyzing query...</span>
              </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Quick Suggestion Pills */}
          <div style={{
            background: "#FFFFFF",
            padding: "0.45rem 0.75rem",
            borderTop: "1px solid var(--border-light)",
            display: "flex",
            gap: "0.35rem",
            overflowX: "auto",
            whiteSpace: "nowrap"
          }}>
            {quickPills.map((pill, idx) => (
              <button
                key={idx}
                onClick={() => handleSend(pill)}
                style={{
                  background: "#F1F5F9",
                  border: "1px solid #E2E8F0",
                  borderRadius: "14px",
                  padding: "0.25rem 0.6rem",
                  fontSize: "0.68rem",
                  color: "var(--gem-navy)",
                  cursor: "pointer",
                  fontWeight: 600,
                  flexShrink: 0
                }}
              >
                {pill}
              </button>
            ))}
          </div>

          {/* Input Area */}
          <div style={{
            padding: "0.6rem 0.75rem",
            background: "#FFFFFF",
            borderTop: "1px solid var(--border-light)",
            display: "flex",
            gap: "0.4rem",
            alignItems: "center"
          }}>
            <input
              type="text"
              placeholder="Ask about GFR rules, CRAC, RA, or verification..."
              value={inputQuery}
              onChange={e => setInputQuery(e.target.value)}
              onKeyDown={e => e.key === "Enter" && handleSend()}
              style={{
                flex: 1,
                border: "1px solid var(--border-medium)",
                borderRadius: "6px",
                padding: "0.45rem 0.65rem",
                fontSize: "0.78rem",
                outline: "none"
              }}
            />
            <button
              onClick={() => handleSend()}
              disabled={!inputQuery.trim()}
              style={{
                background: inputQuery.trim() ? "var(--gem-orange)" : "#CBD5E1",
                color: "#FFFFFF",
                border: "none",
                borderRadius: "6px",
                width: "34px",
                height: "34px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                cursor: inputQuery.trim() ? "pointer" : "default",
                transition: "background 0.15s ease"
              }}
            >
              <Send size={15} />
            </button>
          </div>

        </div>
      )}

      {/* Standard Clean Floating Action Button (FAB) */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        style={{
          width: "52px",
          height: "52px",
          borderRadius: "50%",
          background: "var(--gem-navy)",
          color: "#FFFFFF",
          border: "none",
          boxShadow: "0 4px 16px rgba(10, 37, 64, 0.25)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          cursor: "pointer",
          transition: "transform 0.15s ease, background-color 0.15s ease",
          position: "relative"
        }}
        onMouseEnter={e => e.currentTarget.style.transform = "scale(1.06)"}
        onMouseLeave={e => e.currentTarget.style.transform = "scale(1.0)"}
        title={isOpen ? "Close GeM Assistant" : "GeM AI Compliance Assistant"}
      >
        {isOpen ? (
          <X size={22} color="#FFFFFF" />
        ) : (
          <>
            <Bot size={24} color="#FFFFFF" />
            <span style={{
              position: "absolute",
              top: "3px",
              right: "3px",
              width: "11px",
              height: "11px",
              borderRadius: "50%",
              background: "#10B981",
              border: "2px solid #FFFFFF"
            }} />
          </>
        )}
      </button>

    </div>
  );
}
